server.port: 8080

server.address: 0.0.0.0
spring.application.name: flight-system-gateway
services:
  urls:
    FLIGHT_SERVICE_URL: http://localhost:8070/api/v1/flights
    PRIVILEGE_SERVICE_URL: http://localhost:8050/api/v1/privilege
    TICKETS_SERVICE_URL: http://localhost:8060/api/v1/tickets
spring:
  profiles:
    active: test